version: '3.8'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 'MyStrongPassw0rd!'
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data: